In [36]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
ts, xs = ([297527.99475880736,
  297528.18350366614,
  297528.3486924204,
  297528.55370268493,
  297528.8584375801,
  297529.1314477978,
  297529.5881146017,
  297529.8990818379,
  297530.29651270574,
  297530.8022574018,
  297531.2950760126,
  297531.7799306989,
  297532.2964077384,
  297532.8982239754,
  297533.29521496216,
  297533.9372805078,
  297534.6631190477,
  297535.3914700071,
  297536.15786218544,
  297536.80112579354,
  297537.73817220156,
  297538.5159325687,
  297539.30559917656,
  297540.0964887672,
  297541.14490627137,
  297542.136129794,
  297543.01341845,
  297543.84839469835,
  297544.67383100186,
  297545.6947376251,
  297546.63571615476,
  297547.7813311444,
  297548.69666404,
  297549.67464544263,
  297550.7413548262,
  297551.96781429695,
  297552.9632882414,
  297554.0351870892,
  297555.2584239117,
  297556.3843284526,
  297557.4683850096,
  297558.47672047315,
  297560.0069218027,
  297561.30285341234,
  297562.88418591605,
  297564.3337768644],
 [0,
  100,
  200,
  300,
  400,
  500,
  600,
  700,
  800,
  900,
  1000,
  1100,
  1200,
  1300,
  1400,
  1500,
  1600,
  1700,
  1800,
  1900,
  2000,
  2100,
  2200,
  2300,
  2400,
  2500,
  2600,
  2700,
  2800,
  2900,
  3000,
  3100,
  3200,
  3300,
  3400,
  3500,
  3600,
  3700,
  3800,
  3900,
  4000,
  4100,
  4200,
  4300,
  4400,
  4500])

In [26]:
vx = np.array(xs)
vt = np.array(ts)
alpha = 0.1

In [39]:
dx = vx[1:]-vx[:-1]
dt = vt[1:]-vt[:-1]
sx = vx[:-1]
nf = 1 / np.mean(dx)
nx = sx * nf
dnx = dx * nf
dtx = dt / dx
wx0 = np.exp( - (nx[-1] - nx) * alpha)
wx = wx0 / np.sum(wx0)

In [51]:
y = dtx
x = np.array([nx, dx])

In [52]:
y[:]

array([ 0.00188745,  0.00165189,  0.0020501 ,  0.00304735,  0.0027301 ,
        0.00456667,  0.00310967,  0.00397431,  0.00505745,  0.00492819,
        0.00484855,  0.00516477,  0.00601816,  0.00396991,  0.00642066,
        0.00725839,  0.00728351,  0.00766392,  0.00643264,  0.00937046,
        0.0077776 ,  0.00789667,  0.0079089 ,  0.01048418,  0.00991224,
        0.00877289,  0.00834976,  0.00825436,  0.01020907,  0.00940979,
        0.01145615,  0.00915333,  0.00977981,  0.01066709,  0.01226459,
        0.00995474,  0.01071899,  0.01223237,  0.01125905,  0.01084057,
        0.01008335,  0.01530201,  0.01295932,  0.01581333,  0.01449591])

In [53]:
lr = LinearRegression().fit(np.transpose(x), y, sample_weight = wx)

In [54]:
res = 0
for j in range(np.max(vx), 40000, int(1/nf)):
    xf = np.array([j*nf, 1]).reshape([1,2])
    res += lr.predict(xf) / nf
    print(res)

[ 1.75306049]
[ 3.53350151]
[ 5.34132307]
[ 7.17652515]
[ 9.03910777]
[ 10.92907093]
[ 12.84641461]
[ 14.79113883]
[ 16.76324358]
[ 18.76272886]
[ 20.78959468]
[ 22.84384103]
[ 24.92546791]
[ 27.03447532]
[ 29.17086327]
[ 31.33463175]
[ 33.52578076]
[ 35.7443103]
[ 37.99022038]
[ 40.26351099]
[ 42.56418213]
[ 44.89223381]
[ 47.24766602]
[ 49.63047876]
[ 52.04067203]
[ 54.47824584]
[ 56.94320018]
[ 59.43553505]
[ 61.95525045]
[ 64.50234639]
[ 67.07682286]
[ 69.67867986]
[ 72.3079174]
[ 74.96453546]
[ 77.64853406]
[ 80.3599132]
[ 83.09867286]
[ 85.86481306]
[ 88.65833379]
[ 91.47923506]
[ 94.32751685]
[ 97.20317918]
[ 100.10622204]
[ 103.03664544]
[ 105.99444936]
[ 108.97963382]
[ 111.99219882]
[ 115.03214434]
[ 118.0994704]
[ 121.19417699]
[ 124.31626411]
[ 127.46573177]
[ 130.64257996]
[ 133.84680868]
[ 137.07841793]
[ 140.33740772]
[ 143.62377804]
[ 146.93752889]
[ 150.27866027]
[ 153.64717219]
[ 157.04306464]
[ 160.46633762]
[ 163.91699114]
[ 167.39502519]
[ 170.90043977]
[ 174.43323

In [43]:
lr.predict(np.transpose(xf))

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 12.3922128])

In [49]:
res

array([ 266905.96833771])

In [55]:
def forecast_timeleft(steps, times, final_step, alpha=0.1):
    vx = np.array(steps)
    vt = np.array(times)
    dx = vx[1:]-vx[:-1]
    dt = vt[1:]-vt[:-1]
    sx = vx[:-1]
    nf = 1 / np.mean(dx)
    nx = sx * nf
    dnx = dx * nf
    dtx = dt / dx
    wx0 = np.exp( - (nx[-1] - nx) * alpha)
    wx = wx0 / np.sum(wx0)
    
    y = dtx
    x = np.array([nx, dx])
    
    lr = LinearRegression().fit(np.transpose(x), y, sample_weight = wx)
    
    res = 0
    for j in range(np.max(vx), final_step, int(1/nf)):
        xf = np.array([j*nf, 1]).reshape([1,2])
        res += lr.predict(xf) / nf
    return res